package dev.lightlogin.paper.world;

import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.generator.BiomeProvider;
import org.bukkit.generator.ChunkGenerator;
import org.bukkit.generator.WorldInfo;

import java.util.Random;

/**
 * A chunk generator that produces nothing at all.
 *
 * <p>This is what makes the login world genuinely empty. Setting {@code WorldType.FLAT} with an empty
 * layer list only works in the overworld: a world created in the End dimension is generated by the
 * End's own generator, so the central island, the obsidian pillars and the End's other terrain appear
 * regardless of the flat settings. That is a real regression that shipped once: the world was created
 * with {@code environment(THE_END)} and the player could see End blocks in what was supposed to be a
 * blank staging world.</p>
 *
 * <p>Supplying a generator overrides terrain generation in every dimension, so the same code path
 * gives an empty overworld and an empty End. The dimension then only decides the sky, the lighting
 * and the ambience, which is exactly the distinction the configuration promises.</p>
 *
 * <p>Every generation stage is switched off twice over: the {@code shouldGenerate*} flags are all
 * false, and the stage methods are overridden to write nothing. Either mechanism alone would do; both
 * together mean a future change to one cannot quietly reintroduce terrain.</p>
 */
public final class EmptyLoginWorldGenerator extends ChunkGenerator {

    private final BiomeProvider biomeProvider;
    private final double spawnY;

    /**
     * @param biomeProvider the biome reported for every position, so the world reads as the End or as
     *                      a plain void rather than as whatever the dimension defaults to
     * @param spawnY        the Y the world's fixed spawn is placed at
     */
    public EmptyLoginWorldGenerator(BiomeProvider biomeProvider, double spawnY) {
        this.biomeProvider = biomeProvider;
        this.spawnY = spawnY;
    }

    // --------------------------------------------------------------- nothing is generated

    @Override
    public boolean shouldGenerateNoise() {
        return false;
    }

    @Override
    public boolean shouldGenerateSurface() {
        return false;
    }

    @Override
    public boolean shouldGenerateBedrock() {
        return false;
    }

    @Override
    public boolean shouldGenerateCaves() {
        return false;
    }

    @Override
    public boolean shouldGenerateDecorations() {
        return false;
    }

    @Override
    public boolean shouldGenerateMobs() {
        return false;
    }

    @Override
    public boolean shouldGenerateStructures() {
        return false;
    }

    @Override
    public void generateNoise(WorldInfo worldInfo, Random random, int chunkX, int chunkZ, ChunkData chunkData) {
        // Intentionally empty.
    }

    @Override
    public void generateSurface(WorldInfo worldInfo, Random random, int chunkX, int chunkZ, ChunkData chunkData) {
        // Intentionally empty.
    }

    @Override
    public void generateBedrock(WorldInfo worldInfo, Random random, int chunkX, int chunkZ, ChunkData chunkData) {
        // Intentionally empty.
    }

    @Override
    public void generateCaves(WorldInfo worldInfo, Random random, int chunkX, int chunkZ, ChunkData chunkData) {
        // Intentionally empty.
    }

    @Override
    public BiomeProvider getDefaultBiomeProvider(WorldInfo worldInfo) {
        return biomeProvider;
    }

    /** No natural spawns: the world exists for one player to stand still in. */
    @Override
    public boolean canSpawn(World world, int x, int z) {
        return false;
    }

    @Override
    public Location getFixedSpawnLocation(World world, Random random) {
        return new Location(world, 0.5, spawnY, 0.5);
    }
}