package dev.lightlogin.paper.world;

import dev.lightlogin.core.config.VoidWorldConfig;
import org.bukkit.Bukkit;
import org.bukkit.GameRule;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.WorldCreator;
import org.bukkit.block.Biome;
import org.bukkit.block.Block;
import org.bukkit.entity.EnderDragon;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.Collection;
import java.util.Optional;

/**
 * A blank world used to park players while they authenticate.
 *
 * <p>The world is generated by {@link EmptyLoginWorldGenerator}, which writes no terrain at all, and
 * it lives in whichever dimension the configuration names: the End for its dark sky and ambience, or
 * the overworld for a normal sky. Supplying a generator is what makes the emptiness hold in both
 * dimensions; relying on the world type only works in the overworld, because a world created in the
 * End dimension is generated by the End's own generator and comes out with the island and its
 * pillars.</p>
 *
 * <p>Everything that could make the world cost anything is switched off: no terrain, no structures,
 * no mob spawning of any kind, no fire spread, a random tick speed of zero, and the spawn area is not
 * force-loaded. The ender dragon is refused separately, by {@link LoginWorldGuard}, since no game rule
 * covers it.</p>
 *
 * <h2>Leftover blocks are cleaned, not complained about</h2>
 *
 * <p>A world in the End dimension is the End as far as the server is concerned, so the dragon fight
 * initialises and places the End's exit portal. With no terrain to derive a height from it lands on
 * the world floor: a small cluster of bedrock at the origin, a hundred blocks below the login
 * position, invisible and unreachable. Earlier versions of this class refused to use the world when
 * they found it, which was wrong twice over — the world was perfectly usable, and the block is
 * recreated whenever the world is, so deleting the world never converged either.</p>
 *
 * <p>So the world is always offered for use, and anything unexpected in it is simply cleared at
 * startup. A stray artefact is removed and the world is empty again. Genuine terrain is left alone,
 * because clearing thousands of blocks is not something a plugin should do to a world on a hunch;
 * that case is reported instead, with the folder to delete if the operator wants it gone. Either way
 * players can log in.</p>
 *
 * <p>This is marked experimental in the configuration because a second world still has a real cost:
 * it keeps its own chunk cache and appears in the world list.</p>
 */
public final class VoidWorldService {

    /** Half-extent of the area examined for leftover blocks. */
    private static final int SAMPLE_RADIUS = 16;

    /** Spacing between samples. Also the margin blocks are cleared within, so nothing is missed. */
    private static final int SAMPLE_STEP = 8;

    /** Layers of margin above and below a find, so a partly buried artefact goes entirely. */
    private static final int VERTICAL_CLEAR_MARGIN = 2;

    /**
     * The largest region that will be cleared without asking.
     *
     * <p>The End's exit portal occupies a handful of blocks; a generated island occupies tens of
     * thousands. This sits between them, so an artefact is removed silently and real terrain is never
     * quietly deleted.</p>
     */
    private static final long MAX_CLEAR_VOLUME = 32_768L;

    private final JavaPlugin plugin;
    private final VoidWorldConfig config;
    private World world;

    public VoidWorldService(JavaPlugin plugin, VoidWorldConfig config) {
        this.plugin = plugin;
        this.config = config;
    }

    /**
     * Creates or loads the login world and clears anything that should not be in it.
     *
     * @return true when the world is ready for use
     */
    public boolean initialise() {
        if (!config.enabled()) {
            return false;
        }
        try {
            World existing = Bukkit.getWorld(config.worldName());
            if (existing != null) {
                this.world = existing;
                tidy(existing);
                return true;
            }

            boolean end = config.dimension() == VoidWorldConfig.Dimension.END;
            World.Environment environment = end ? World.Environment.THE_END : World.Environment.NORMAL;
            // The biome is chosen per dimension purely for ambience. An End-dimension world reporting
            // the_void would read as a generation bug, and vice versa.
            Biome biome = end ? Biome.THE_END : Biome.THE_VOID;

            WorldCreator creator = new WorldCreator(config.worldName())
                    .environment(environment)
                    .generator(new EmptyLoginWorldGenerator(new SingleBiomeProvider(biome), config.spawnY()))
                    .generateStructures(false);
            World created = creator.createWorld();
            if (created == null) {
                plugin.getLogger().warning("The blank login world could not be created; login teleport is disabled.");
                return false;
            }

            created.setSpawnLocation(0, (int) config.spawnY(), 0);
            created.setDifficulty(org.bukkit.Difficulty.PEACEFUL);
            // Spigot names these after the vanilla game rule ids. The old Bukkit aliases
            // (DO_MOB_SPAWNING, DO_DAYLIGHT_CYCLE, ANNOUNCE_ADVANCEMENTS and friends) do not exist
            // in this API, and doFireTick has been replaced by a fire spread radius.
            created.setGameRule(GameRule.SPAWN_MOBS, false);
            created.setGameRule(GameRule.SPAWN_MONSTERS, false);
            created.setGameRule(GameRule.SPAWN_PATROLS, false);
            created.setGameRule(GameRule.SPAWN_WANDERING_TRADERS, false);
            created.setGameRule(GameRule.SPAWN_PHANTOMS, false);
            created.setGameRule(GameRule.SPAWN_WARDENS, false);
            created.setGameRule(GameRule.ADVANCE_TIME, false);
            created.setGameRule(GameRule.ADVANCE_WEATHER, false);
            created.setGameRule(GameRule.SHOW_ADVANCEMENT_MESSAGES, false);
            created.setGameRule(GameRule.FALL_DAMAGE, false);
            created.setGameRule(GameRule.MOB_GRIEFING, false);
            created.setGameRule(GameRule.IMMEDIATE_RESPAWN, true);
            // Fire cannot spread, so nothing in an empty world can start one or be consumed by one.
            created.setGameRule(GameRule.FIRE_SPREAD_RADIUS_AROUND_PLAYER, 0);
            // Nothing in this world should ever change: it exists only as a place to stand.
            created.setGameRule(GameRule.RANDOM_TICK_SPEED, 0);
            // The spawn area is not force-loaded; the world is occupied only while someone logs in.
            created.setKeepSpawnInMemory(false);

            this.world = created;
            // The generator should have produced nothing, but the dragon fight's exit portal is
            // placed when the world initialises, so the result is checked rather than assumed.
            tidy(created);
            return true;
        } catch (RuntimeException e) {
            plugin.getLogger().warning("Failed to prepare the blank login world: " + e.getMessage());
            return false;
        }
    }

    /**
     * Clears anything unexpected from the world, and reports what it cannot clear.
     *
     * <p>Runs on every startup, so a block the server recreates is removed again next time rather than
     * accumulating, and the world is empty from the operator's point of view without them doing
     * anything.</p>
     */
    private void tidy(World candidate) {
        Foreign foreign = scan(candidate);
        if (foreign.none()) {
            return;
        }

        int y0 = Math.max(candidate.getMinHeight(), foreign.minY() - VERTICAL_CLEAR_MARGIN);
        int y1 = Math.min(candidate.getMaxHeight() - 1, foreign.maxY() + VERTICAL_CLEAR_MARGIN);
        int x0 = foreign.minX() - SAMPLE_STEP;
        int x1 = foreign.maxX() + SAMPLE_STEP;
        int z0 = foreign.minZ() - SAMPLE_STEP;
        int z1 = foreign.maxZ() + SAMPLE_STEP;
        long volume = (long) (x1 - x0 + 1) * (y1 - y0 + 1) * (z1 - z0 + 1);

        if (!isArtefactSized(volume)) {
            plugin.getLogger().warning("The blank login world contains " + foreign.describe() + '.');
            plugin.getLogger().warning("That is far more than a stray artefact, so it has been left alone");
            plugin.getLogger().warning("rather than deleted on a guess. Login still works. If you want it");
            plugin.getLogger().warning("gone, stop the server, delete this folder and restart:");
            plugin.getLogger().warning("    " + candidate.getWorldFolder().getAbsolutePath());
            return;
        }

        int cleared = clear(candidate, x0, x1, y0, y1, z0, z1);
        plugin.getLogger().info("Cleared " + cleared + " leftover block(s) from the login world ("
                + foreign.describe() + "); it is empty again.");

        // Verify rather than assume, because assuming is what went wrong before.
        Foreign remaining = scan(candidate);
        if (!remaining.none()) {
            plugin.getLogger().warning("Some blocks remain in the login world: " + remaining.describe() + '.');
        }
    }

    /** Clears a region to air, without physics, and reports how many blocks were removed. */
    private int clear(World candidate, int x0, int x1, int y0, int y1, int z0, int z1) {
        int cleared = 0;
        for (int x = x0; x <= x1; x++) {
            for (int z = z0; z <= z1; z++) {
                for (int y = y0; y <= y1; y++) {
                    Block block = candidate.getBlockAt(x, y, z);
                    if (!isAirLike(block.getType())) {
                        // No physics: the world is being emptied, not edited, and an update cascade
                        // over thousands of blocks would be pure cost.
                        block.setType(Material.AIR, false);
                        cleared++;
                    }
                }
            }
        }
        return cleared;
    }

    /**
     * Examines the login area and reports what is not air.
     *
     * <p>Chunks are generated before being read, so this can never pass by examining nothing: the
     * first version of this check ran before the spawn area existed, found no blocks because there
     * were none to find, and so passed once and then reported a false alarm on every restart.</p>
     *
     * <p>Blocks are read directly rather than through the height map, and all four air materials count
     * as empty. An empty world in a modern dimension is filled with {@code void_air}, not {@code air},
     * so comparing against {@link Material#AIR} alone reported a perfectly empty world as full.</p>
     */
    private Foreign scan(World candidate) {
        int minimumHeight = candidate.getMinHeight();
        int ceiling = candidate.getMaxHeight();
        int blocks = 0;
        Material sample = Material.AIR;
        int minX = Integer.MAX_VALUE;
        int maxX = Integer.MIN_VALUE;
        int minY = Integer.MAX_VALUE;
        int maxY = Integer.MIN_VALUE;
        int minZ = Integer.MAX_VALUE;
        int maxZ = Integer.MIN_VALUE;

        for (int x = -SAMPLE_RADIUS; x <= SAMPLE_RADIUS; x += SAMPLE_STEP) {
            for (int z = -SAMPLE_RADIUS; z <= SAMPLE_RADIUS; z += SAMPLE_STEP) {
                candidate.getChunkAt(x >> 4, z >> 4);
                for (int y = minimumHeight; y < ceiling; y++) {
                    Material material = candidate.getBlockAt(x, y, z).getType();
                    if (isAirLike(material)) {
                        continue;
                    }
                    if (blocks == 0) {
                        sample = material;
                    }
                    blocks++;
                    minX = Math.min(minX, x);
                    maxX = Math.max(maxX, x);
                    minY = Math.min(minY, y);
                    maxY = Math.max(maxY, y);
                    minZ = Math.min(minZ, z);
                    maxZ = Math.max(maxZ, z);
                }
            }
        }
        return new Foreign(blocks, sample, minX, maxX, minY, maxY, minZ, maxZ);
    }

    /** Whether a region is small enough to be a stray artefact rather than generated terrain. */
    static boolean isArtefactSized(long volume) {
        return volume <= MAX_CLEAR_VOLUME;
    }

    /**
     * Whether a material is a form of emptiness.
     *
     * <p>Bukkit has exactly four, and these are all of them: {@code air}, {@code void_air},
     * {@code cave_air} and {@code structure_void}. Only the first is {@link Material#AIR}, and the
     * other three are what an empty world in a modern dimension actually contains, which is what made
     * an earlier equality test wrong.</p>
     *
     * <p>Deliberately plain equality rather than {@link Material#isAir()}. That method resolves the
     * material through the server's block registry, which means it throws when there is no running
     * server, and it says nothing these four comparisons do not.</p>
     */
    static boolean isAirLike(Material material) {
        return material == Material.AIR
                || material == Material.VOID_AIR
                || material == Material.CAVE_AIR
                || material == Material.STRUCTURE_VOID;
    }

    /** What a scan found, in enough detail to describe it and to clear it. */
    private record Foreign(int blocks, Material sample, int minX, int maxX, int minY, int maxY,
                           int minZ, int maxZ) {

        boolean none() {
            return blocks == 0;
        }

        String describe() {
            return blocks + " block(s) of " + sample + " spanning y=" + minY + " to y=" + maxY;
        }
    }

    /** Whether the login world is available for use. Always true once it exists. */
    public boolean isAvailable() {
        return world != null;
    }

    /** The login world, if any. */
    public Optional<World> world() {
        return Optional.ofNullable(world);
    }

    /** Whether a world is this service's login world. */
    public boolean isLoginWorld(World candidate) {
        return world != null && candidate != null && candidate.getName().equals(world.getName());
    }

    /**
     * Removes any ender dragon that found its way into the login world.
     *
     * <p>A world in the End dimension is the End as far as the server is concerned, and there is no
     * game rule for the dragon. {@link LoginWorldGuard} also refuses one at its spawn event; this is
     * the net underneath that, for a dragon the dragon fight adds without raising an event.</p>
     *
     * @return how many were removed, so the caller can log it once
     */
    public int removeDragons() {
        if (world == null) {
            return 0;
        }
        Collection<EnderDragon> dragons = world.getEntitiesByClass(EnderDragon.class);
        for (EnderDragon dragon : dragons) {
            dragon.remove();
        }
        return dragons.size();
    }

    /** The spawn location used for authentication, centred on the block. */
    public Location spawnLocation() {
        if (world == null) {
            return null;
        }
        Location spawn = world.getSpawnLocation();
        // Centre on the block so a player never spawns on a corner and drifts.
        spawn.setX(0.5);
        spawn.setZ(0.5);
        spawn.setY(config.spawnY());
        return spawn;
    }

    /** Teleports a player into the login world. */
    public boolean teleportIn(Player player) {
        Location target = spawnLocation();
        if (target == null) {
            return false;
        }
        return player.teleport(target);
    }

    /** The world name, for logging. */
    public String worldName() {
        return config.worldName();
    }

    /** Configuration accessor. */
    public VoidWorldConfig config() {
        return config;
    }
}