package dev.lightlogin.paper.world;

import dev.lightlogin.core.config.VoidWorldConfig;
import org.bukkit.Bukkit;
import org.bukkit.GameRule;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.WorldCreator;
import org.bukkit.block.Biome;
import org.bukkit.block.Block;
import org.bukkit.entity.EnderDragon;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.Collection;
import java.util.Optional;

/**
 * A blank world used to park players while they authenticate.
 *
 * <p>The world is generated by {@link EmptyLoginWorldGenerator}, which writes no terrain at all, and
 * it lives in whichever dimension the configuration names: the End for its dark sky and ambience, or
 * the overworld for a normal sky. Supplying a generator is what makes the emptiness hold in both
 * dimensions; relying on the world type only works in the overworld, because a world created in the
 * End dimension is generated by the End's own generator and comes out with the island and its
 * pillars.</p>
 *
 * <p>Everything that could make the world cost anything is switched off: no terrain, no structures,
 * no mob spawning of any kind, no fire spread, a random tick speed of zero, and the spawn area is not
 * force-loaded. The ender dragon is refused separately, by {@link LoginWorldGuard}, since no game rule
 * covers it.</p>
 *
 * <p>Because an empty world can only be guaranteed at generation time, the world is checked on
 * startup and the result is trusted. A folder generated by an earlier version still holds the terrain
 * it was generated with, and no generator change can remove it, so the check reports that rather than
 * letting players stand next to an End island. When the check fails, teleporting is disabled and
 * players authenticate where they are — a worse experience than an empty world, and a much better one
 * than a broken one.</p>
 *
 * <p>This is marked experimental in the configuration because a second world still has a real cost:
 * it keeps its own chunk cache and appears in the world list.</p>
 */
public final class VoidWorldService {

    /** Half-extent of the area sampled when checking that the world is actually empty. */
    private static final int EMPTINESS_SAMPLE_RADIUS = 16;

    /** Spacing between samples inside that area. */
    private static final int EMPTINESS_SAMPLE_STEP = 8;

    private final JavaPlugin plugin;
    private final VoidWorldConfig config;
    private World world;
    private boolean empty;

    public VoidWorldService(JavaPlugin plugin, VoidWorldConfig config) {
        this.plugin = plugin;
        this.config = config;
    }

    /**
     * Creates or loads the login world.
     *
     * @return true when the world is ready and usable
     */
    public boolean initialise() {
        if (!config.enabled()) {
            return false;
        }
        try {
            World existing = Bukkit.getWorld(config.worldName());
            if (existing != null) {
                this.world = existing;
                this.empty = looksEmpty(existing);
                if (!empty) {
                    reportNotEmpty(existing);
                }
                return empty;
            }

            boolean end = config.dimension() == VoidWorldConfig.Dimension.END;
            World.Environment environment = end ? World.Environment.THE_END : World.Environment.NORMAL;
            // The biome is chosen per dimension purely for ambience. An End-dimension world reporting
            // the_void would read as a generation bug, and vice versa.
            Biome biome = end ? Biome.THE_END : Biome.THE_VOID;

            WorldCreator creator = new WorldCreator(config.worldName())
                    .environment(environment)
                    .generator(new EmptyLoginWorldGenerator(new SingleBiomeProvider(biome), config.spawnY()))
                    .generateStructures(false);
            World created = creator.createWorld();
            if (created == null) {
                plugin.getLogger().warning("The blank login world could not be created; login teleport is disabled.");
                return false;
            }

            created.setSpawnLocation(0, (int) config.spawnY(), 0);
            created.setDifficulty(org.bukkit.Difficulty.PEACEFUL);
            // Spigot names these after the vanilla game rule ids. The old Bukkit aliases
            // (DO_MOB_SPAWNING, DO_DAYLIGHT_CYCLE, ANNOUNCE_ADVANCEMENTS and friends) do not exist
            // in this API, and doFireTick has been replaced by a fire spread radius.
            created.setGameRule(GameRule.SPAWN_MOBS, false);
            created.setGameRule(GameRule.SPAWN_MONSTERS, false);
            created.setGameRule(GameRule.SPAWN_PATROLS, false);
            created.setGameRule(GameRule.SPAWN_WANDERING_TRADERS, false);
            created.setGameRule(GameRule.SPAWN_PHANTOMS, false);
            created.setGameRule(GameRule.SPAWN_WARDENS, false);
            created.setGameRule(GameRule.ADVANCE_TIME, false);
            created.setGameRule(GameRule.ADVANCE_WEATHER, false);
            created.setGameRule(GameRule.SHOW_ADVANCEMENT_MESSAGES, false);
            created.setGameRule(GameRule.FALL_DAMAGE, false);
            created.setGameRule(GameRule.MOB_GRIEFING, false);
            created.setGameRule(GameRule.IMMEDIATE_RESPAWN, true);
            // Fire cannot spread, so nothing in an empty world can start one or be consumed by one.
            created.setGameRule(GameRule.FIRE_SPREAD_RADIUS_AROUND_PLAYER, 0);
            // Nothing in this world should ever change: it exists only as a place to stand.
            created.setGameRule(GameRule.RANDOM_TICK_SPEED, 0);
            // The spawn area is not force-loaded; the world is occupied only while someone logs in.
            created.setKeepSpawnInMemory(false);

            this.world = created;
            // Verifies the generator actually took effect rather than assuming it did, and forces the
            // spawn area to generate now so the check is not looking at ungenerated chunks.
            this.empty = looksEmpty(created);
            if (!empty) {
                reportNotEmpty(created);
            }
            return empty;
        } catch (RuntimeException e) {
            plugin.getLogger().warning("Failed to prepare the blank login world: " + e.getMessage());
            return false;
        }
    }

    /**
     * Whether the world holds nothing but air.
     *
     * <p>Uses the height map, which is the cheap way to ask "is there anything here": in an empty world
     * every column reports the bottom of the world, and any generated terrain reports its own height.
     * Sampling spans a few chunks around the origin, which is where the End's island would be, so a
     * world generated by an earlier version is caught rather than trusted.</p>
     */
    private boolean looksEmpty(World candidate) {
        int floor = candidate.getMinHeight();
        for (int x = -EMPTINESS_SAMPLE_RADIUS; x <= EMPTINESS_SAMPLE_RADIUS; x += EMPTINESS_SAMPLE_STEP) {
            for (int z = -EMPTINESS_SAMPLE_RADIUS; z <= EMPTINESS_SAMPLE_RADIUS; z += EMPTINESS_SAMPLE_STEP) {
                Block highest = candidate.getHighestBlockAt(x, z);
                if (highest.getType() != Material.AIR && highest.getY() > floor) {
                    return false;
                }
            }
        }
        return true;
    }

    /** Explains exactly what is wrong and what to do, because the fix is outside the plugin. */
    private void reportNotEmpty(World offending) {
        plugin.getLogger().warning("The blank login world '" + offending.getName() + "' is not empty.");
        plugin.getLogger().warning("It contains generated blocks, which no generator change can remove: the");
        plugin.getLogger().warning("terrain was written when the world was first created.");
        plugin.getLogger().warning("To fix it, stop the server, delete this folder and restart:");
        plugin.getLogger().warning("    " + offending.getWorldFolder().getAbsolutePath());
        plugin.getLogger().warning("The world will be recreated empty. Until then, login teleporting is");
        plugin.getLogger().warning("disabled and players authenticate where they are.");
    }

    /** Whether the login world is available for use. */
    public boolean isAvailable() {
        return world != null && empty;
    }

    /** The login world, if any. */
    public Optional<World> world() {
        return Optional.ofNullable(world);
    }

    /** Whether a world is this service's login world. */
    public boolean isLoginWorld(World candidate) {
        return world != null && candidate != null && candidate.getName().equals(world.getName());
    }

    /**
     * Removes any ender dragon that found its way into the login world.
     *
     * <p>A world in the End dimension is the End as far as the server is concerned, and there is no
     * game rule for the dragon. {@link LoginWorldGuard} also refuses one at its spawn event; this is
     * the net underneath that, for a dragon the dragon fight adds without raising an event.</p>
     *
     * @return how many were removed, so the caller can log it once
     */
    public int removeDragons() {
        if (world == null) {
            return 0;
        }
        Collection<EnderDragon> dragons = world.getEntitiesByClass(EnderDragon.class);
        for (EnderDragon dragon : dragons) {
            dragon.remove();
        }
        return dragons.size();
    }

    /** The spawn location used for authentication, centred on the block. */
    public Location spawnLocation() {
        if (world == null) {
            return null;
        }
        Location spawn = world.getSpawnLocation();
        // Centre on the block so a player never spawns on a corner and drifts.
        spawn.setX(0.5);
        spawn.setZ(0.5);
        spawn.setY(config.spawnY());
        return spawn;
    }

    /** Teleports a player into the login world. */
    public boolean teleportIn(Player player) {
        Location target = spawnLocation();
        if (target == null) {
            return false;
        }
        return player.teleport(target);
    }

    /** The world name, for logging. */
    public String worldName() {
        return config.worldName();
    }

    /** Configuration accessor. */
    public VoidWorldConfig config() {
        return config;
    }
}